[Desktop Entry]
Name=Awesome
Type=X-GNOME-Metatheme
Comment=Don't Be Efficient. Just Be Awesome.

[X-GNOME-Metatheme]
GtkTheme=Awesome
MetacityTheme=Awesome
IconTheme=Gion
GtkColorScheme=fg_color:#000000000000,bg_color:#f5f5f5f5f5f5,text_color:#000000000000,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#5ad65ad65ad6,tooltip_fg_color:#000000000000,tooltip_bg_color:#000000000000
CursorTheme=default
CursorSize=18
NotificationTheme=slider
