#!/bin/sh

export PATH=~/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/games:/usr/games

## background
WALLPAPER=~/.wallpapers/wallpaper.jpg
if [ -h $WALLPAPER  ]; then
    feh --no-fehbg --bg-scale $WALLPAPER
else
    xsetroot -solid "#073542"
fi

### statusbar
if [ "$(which slstatus)" ]; then
    LC_TIME=en_US.UTF-8 slstatus &
else
    xsetroot -name "$(hostname -f)"
fi

### display color temperature
systemd-run --user --unit=redshift bash -c '/usr/bin/redshift -m randr -l 47.3:11.6 -t 5700:3000 -b 1.0:0.8' >/dev/null 2>&1

### system info
nohup conky -c ~/.conky/system.conkyrc >/dev/null 2>&1 &

exec ~/.config/X11/dwm
