#!/bin/sh

## dbus
STARTDBUS=
DBUSLAUNCH=/usr/bin/dbus-launch

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] && [ -x "$DBUSLAUNCH" ]; then
    STARTDBUS=yes
fi

if [ -n "$STARTDBUS" ]; then
    eval $($DBUSLAUNCH --exit-with-session --sh-syntax)
fi

if [ -n "$DBUS_SESSION_BUS_ADDRESS" ] && \
    [ -x "/usr/bin/dbus-update-activation-environment" ]; then
    (
        unset XDG_SEAT
        unset XDG_SESSION_ID
        unset XDG_VTNR
        dbus-update-activation-environment --verbose --systemd --all
    )
fi

## background
xsetroot -solid "#073542"

## f.lux
~/.bin/xflux -l 49.97000122 -g 8.27000046

## keys
xbindkeys

### statusbar
LC_TIME=en_US.UTF-8 /usr/local/bin/slstatus &

exec ~/.config/X11/dwm
